"""Create user_assets table and relationships

Revision ID: 2e0d2b427d7a
Revises: 39555ec57ca9
Create Date: 2024-10-28 07:55:32.923015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0d2b427d7a'
down_revision = '39555ec57ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_symbol', sa.String(length=256), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('avg_purchase_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_symbol', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('asset_price_at_purchase', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('asset_quantity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('asset_quantity')
        batch_op.drop_column('asset_price_at_purchase')
        batch_op.drop_column('asset_symbol')

    op.drop_table('user_assets')
    # ### end Alembic commands ###
