"""Create transactions table

Revision ID: 39555ec57ca9
Revises: 8653d2db3c58
Create Date: 2024-10-27 23:06:29.199955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39555ec57ca9'
down_revision = '8653d2db3c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('source_account_number', sa.String(length=36), nullable=False),
    sa.Column('target_account_number', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
