"""Change balance column from users table

Revision ID: 4efb5c585c16
Revises: 8276484d9de6
Create Date: 2024-10-27 17:28:53.749263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4efb5c585c16'
down_revision = '8276484d9de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)

    # ### end Alembic commands ###
